### ISSUE TITLE
Restyle code block

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/learncms#59]
![sketch](https://cloud.githubusercontent.com/assets/741789/10052742/02bd2cdc-61ee-11e5-9039-e20cd609796f.png)

**Comment by JoeGermuska** [comment]
If the issue is essentially about color, it is very easy to switch to any of these:

http://jmblog.github.io/color-themes-for-google-code-prettify/

My understanding is that the summer content team thought it was strange to use light backgrounds for the code when we all generally promote dark backgrounds. I have no opinion.

If you want the specific colors in the sketch, would you be game to take one of those CSS themes and take a crack at it? Or, barring that, make explicit the CSS hex colors for the various things?

It also crossed my mind that switching to [CodeMirror](https://codemirror.net/), which drives the CMS content editor, might be a route to the more elaborate ideas you had about annotating code blocks. The main concern with that is figuring out the balance between simple enough authoring vs the gain of more clarity/information in the final presentation -- but I'd be game to talk more about that.
