### ISSUE TITLE
Escape entities for HTML codeblocks

### ISSUE THREAD

**Issue by nicolezhu** [NUKnightLab/learncms#62]

**Comment by duner** [comment]
The relevant code lives in /learncms/refresolvers.py I believe. Goal is so that you don't have to write the unicode codes for characters like `<`, and `&` when drafting lessons.

**Comment by duner** [comment]
Solved in #68.

**Comment by JoeGermuska** [comment]
@emilywithrow this kinda works, but our strategy involves parsing HTML, manipulating the DOM, and then replacing a substring of the lesson content with the modified, entity-escaped version.

This leads to some nearly unavoidable loss of precision regarding whitespace, and sometimes changes the markup to close tags, etc. Just how much do you need things preserved exactly vs just how hateful is it to have to write entity escapes?

There's a chance we could try to do it with string manipulation instead of through the DOM... using regular expressions to muck with HTML can be messy, but it could work. let's talk, here or f2f

**Comment by emilywithrow** [comment]
So... editorially, this is a HUGE time suck, and makes the code really hard to read/parse visually. I'd love it if you'd continue to explore solutions.

**Comment by JoeGermuska** [comment]
Closed with #68. There are some minor weirdnesses around the first item in the code block, but I think those are attributable to the `prettyprint` library, or possibly to something in our `code-block` component. But if that's an issue, let's open another ticket. I think it might require switching away from `prettyprint`
