### ISSUE TITLE
Code blocks have gray background highlight

### ISSUE THREAD

**Issue by emilywithrow** [NUKnightLab/learncms#69]
![screen shot 2015-10-07 at 12 41 27 pm](https://cloud.githubusercontent.com/assets/798614/10345661/d672e41a-6cf0-11e5-9545-ef53a5ce5917.png)

**Comment by JoeGermuska** [comment]
I'm working on this. But the general warning I have is to not be so specific with the CSS selectors, because it makes it hard for other things to over-ride them.

**Comment by zachwise** [comment]
I added specificity in order to deal with #61. This change doesn't break that does it?

**Comment by JoeGermuska** [comment]
Did you reopen this because you found a specific problem? If it's with #61, we should reopen that one and be more specific about what's not working, because this issue doesn't occur any more -- thus, closing this ticket.

All I did was [remove the `#step-content` part of the selector](https://github.com/NUKnightLab/learncms/commit/5442c700d103e9bb665a1d0f4221cbe90b6f3113#diff-a6b2a096f74d60cf2216dbac7015d7d7L221).
